version: "3"
services:
  nginx:
    image: nginx
    entrypoint: ["nginx","-g","daemon off;"]
    ports:
      - 80:80
    volumes: 
      - ./nginxConfig/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  backend:
    image: nptn90/reactdemo:0.0.2-SNAPSHOT
    depends_on:
      - my-db
    environment: 
      ENVIROMENT: docker
      DATABASE: mysql
      DB_USERNAME: root
      DB_PASSWORD: Matkhau1990@
      DB_DIALEC: org.hibernate.dialect.MySQL5Dialect
      DATABASE_URL: jdbc:mysql://docker-mysql:3306/demoreactjs
  my-db: 
    image: mysql:5.7
    container_name: docker-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'demoreactjs'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Matkhau1990@'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Matkhau1990@'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3305:3306'
    expose:
      # Opens port 3306 on the container
      - '3305'
      # Where our data will be persisted
    volumes:
      - volume-db:/var/lib/mysql
    healthcheck: 
      test: "/usr/bin/mysql --user=root --password=Matkhau1990@--execute \"SHOW DATABASES;\""
      interval: 30s
# Names our volume
volumes:
  volume-db: