server:
  port: 8085
system:
  user:
    username: nhan
    password: nguyen
    fullName: Nhan Nguyen Pham Thanh
    roles: 
      - ADMIN
      - SYSADMIN
    email: nhan.nguyen@wizeline.com
  jwt:
    secret-key: nhantest
    ##minute expired time
    expired-time: 30
#MongoDB
spring:
  profiles:
    active:
    - ${ENVIROMENT:docker}
    - ${DATABASE:mysql}
  jpa:
    hibernate:
      ddl-auto: create